version: '3.0'

services:
    node:
        container_name: mayoral-assignment-node
        command: bash
        build: ./node
        mem_limit: 2048m
        volumes:
            - ${APP_DIR}:/home/app
        working_dir: /home/app
        network_mode: host
